modLoader="javafml"
loaderVersion="[40,)"
license="GNU AGPLv3"

[[mods]]
    modId="quantumrs"
    version="1.0"
    displayName="QuantumRS"
    issueTrackerURL="https://github.com/YarinQuapi/QuantumRS/issues"
    displayURL="https://legacy.curseforge.com/minecraft/mc-mods/quantumrs"
    authors="YarinQuapi"
    description="QuantumRS adds a nearly infinite disk to Refined Storage"


[[dependencies.quantumrs]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quantumrs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quantumrs]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.10.2,)"
    ordering="AFTER"
    side="BOTH"